#!/usr/bin/env node
// Build-time script: sync system-prompt.json → Edge Function TypeScript constant
// Run: node scripts/sync-prompt.mjs
// This ensures the Edge Function always has the latest prompt without manual copy

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const SOURCE = resolve(ROOT, 'shared/system-prompt.json');
const TARGET = resolve(ROOT, 'supabase/functions/ai-chat/_prompt.ts');

if (!existsSync(SOURCE)) {
  console.error(`❌ Source not found: ${SOURCE}`);
  process.exit(1);
}

const json = JSON.parse(readFileSync(SOURCE, 'utf-8'));
const prompt = json.system_prompt;

if (!prompt) {
  console.error('❌ system_prompt field not found in JSON');
  process.exit(1);
}

const tsContent = `// AUTO-GENERATED by scripts/sync-prompt.mjs
// DO NOT EDIT — modify shared/system-prompt.json instead
// Last synced: ${new Date().toISOString()}

export const SYSTEM_PROMPT = ${JSON.stringify(prompt)};
`;

writeFileSync(TARGET, tsContent, 'utf-8');
console.log(`✅ Synced system prompt → ${TARGET}`);
console.log(`   Length: ${prompt.length} chars`);
